import { upperFirst } from '@xiaoye-react/hooks';

interface SelectDataItem {
  label: string;
  value: string;
}

export type SelectData = (string | SelectDataItem)[];

const SELECT_LABELS: Record<string, string> = {
  default: '默认',
  filled: '填充',
  unstyled: '无样式',
  outline: '描边',
  subtle: '柔和',
  light: '浅色',
  gradient: '渐变',
  white: '白色',
  black: '黑色',
  transparent: '透明',
  xs: '超小',
  sm: '小',
  md: '中',
  lg: '大',
  xl: '超大',
  top: '顶部',
  bottom: '底部',
  left: '左侧',
  right: '右侧',
  start: '起始',
  end: '末尾',
  center: '居中',
  horizontal: '水平',
  vertical: '垂直',
  row: '行',
  column: '列',
  true: '是',
  false: '否',
  asc: '升序',
  desc: '降序',
  lightDark: '明暗',
  luminance: '亮度',
  always: '始终',
  hover: '悬停',
  never: '从不',
  click: '点击',
  contextMenu: '右键菜单',
  dots: '圆点',
  none: '无',
  button: '按钮',
  checkbox: '复选框',
  radio: '单选框',
  switch: '开关',
  native: '原生',
  custom: '自定义',
  static: '静态',
  dynamic: '动态',
  auto: '自动',
  manual: '手动',
  fixed: '固定',
  responsive: '响应式',
  contain: '包含',
  cover: '覆盖',
  stretch: '拉伸',
  repeat: '重复',
  round: '圆角',
  square: '方角',
  circle: '圆形',
  pill: '胶囊',
  primary: '主要',
  secondary: '次要',
  success: '成功',
  warning: '警告',
  danger: '危险',
  info: '信息',
  muted: '柔和',
  bright: '亮色',
  dimmed: '暗淡',
  dark: '深色',
  gray: '灰色',
  red: '红色',
  pink: '粉色',
  grape: '葡萄紫',
  violet: '紫罗兰',
  indigo: '靛蓝',
  blue: '蓝色',
  cyan: '青色',
  teal: '蓝绿',
  green: '绿色',
  lime: '青柠',
  yellow: '黄色',
  orange: '橙色',
  'space-between': '两端对齐',
  'flex-start': 'Flex 起点',
  'flex-end': 'Flex 终点',
  regular: '常规',
  compact: '紧凑',
  apart: '分开',
  together: '一起',
  chars: '字符',
  words: '单词',
  lines: '行',
  overlay: '遮罩层',
  transition: '过渡',
};

export function transformSelectData(data: SelectData): SelectDataItem[] {
  return data.map((item) => {
    if (typeof item === 'string') {
      return { label: SELECT_LABELS[item] || upperFirst(item), value: item };
    }

    return { value: item.value, label: SELECT_LABELS[item.label] || upperFirst(item.label) };
  });
}
