// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// Created by Umi Plugin

export interface IConfigFromPluginsJoi {
stagewise?: unknown
live?: boolean
logo?: string
themeConfig?: {

}
extraRehypePlugins?: unknown[]
extraRemarkPlugins?: unknown[]
resolve?: {
docDirs?: unknown[]
atomDirs?: {
type?: string
subType?: string
dir?: string
}[]
codeBlockMode?: ("active" | "passive")
entryFile?: string
forceKebabCaseRouting?: boolean
}
autoAlias?: boolean
rawMd?: {
routeFilter?: (() => any)
contentReplacers?: unknown[]
enableReplaceCodeSrc?: boolean
codeAppend?: (() => any)
}
locales?: ({
id?: string
name?: string
base?: string
}[] | {
id?: string
name?: string
suffix?: ""
}[])
apiParser?: {
unpkgHost?: string
resolveFilter?: (() => any)
parseOptions?: {

}
}
assets?: {

}
sitemap?: {
hostname?: string
exclude?: string[]
}
html2sketch?: {
scriptUrl?: string
}
}
