import { filterProps } from '../../../../core/utils'
import type { MantineStyleProps } from '../style-props.types'

/**
 * 从传入的对象中提取样式属性和其他属性
 * @template T - 传入对象的类型
 * @param {MantineStyleProps & T} others - 包含样式属性和其他属性的对象
 * @returns {{styleProps: MantineStyleProps & {sx?: any}, rest: T}} 包含分离后的样式属性和剩余属性的对象
 */
export function extractStyleProps<T extends Record<string, any>>(
    others: MantineStyleProps & T
): { styleProps: MantineStyleProps & { sx?: any }; rest: T } {
    const {
        m,
        mx,
        my,
        mt,
        mb,
        ml,
        mr,
        me,
        ms,
        p,
        px,
        py,
        pt,
        pb,
        pl,
        pr,
        pe,
        ps,
        bd,
        bdrs,
        bg,
        c,
        opacity,
        ff,
        fz,
        fw,
        lts,
        ta,
        lh,
        fs,
        tt,
        td,
        w,
        miw,
        maw,
        h,
        mih,
        mah,
        bgsz,
        bgp,
        bgr,
        bga,
        pos,
        top,
        left,
        bottom,
        right,
        inset,
        display,
        flex,
        hiddenFrom,
        visibleFrom,
        lightHidden,
        darkHidden,
        sx,
        ...rest
    } = others

    const styleProps = filterProps({
        m,
        mx,
        my,
        mt,
        mb,
        ml,
        mr,
        me,
        ms,
        p,
        px,
        py,
        pt,
        pb,
        pl,
        pr,
        pe,
        ps,
        bd,
        bg,
        c,
        opacity,
        ff,
        fz,
        fw,
        lts,
        ta,
        lh,
        fs,
        tt,
        td,
        w,
        miw,
        maw,
        h,
        mih,
        mah,
        bgsz,
        bgp,
        bgr,
        bga,
        pos,
        top,
        left,
        bottom,
        right,
        inset,
        display,
        flex,
        bdrs,
        hiddenFrom,
        visibleFrom,
        lightHidden,
        darkHidden,
        sx
    })

    return { styleProps, rest: rest as unknown as T }
}
