// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/zhangzhengyang/Desktop/Code/react/UI/react-ui/node_modules/.pnpm/dumi@2.4.47_@babel+core@7.28.4_@swc+helpers@0.5.15_@types+node@26.1.1_@types+react@19.2.17_li_vfk5tpshfcvdy37fi62o2hmy4e/node_modules/dumi/theme-default/layouts/DocLayout/index.js';
