export default {
    index: '组件概览',
    '--basic': { type: 'separator', title: '基础组件' },
    button: 'Button',
    'action-icon': 'ActionIcon',
    'close-button': 'CloseButton',
    anchor: 'Anchor',
    text: 'Text',
    title: 'Title',
    '--layout': { type: 'separator', title: '布局组件' },
    container: 'Container',
    group: 'Group',
    stack: 'Stack',
    paper: 'Paper',
    center: 'Center',
    flex: 'Flex',
    grid: 'Grid',
    'simple-grid': 'SimpleGrid',
    'aspect-ratio': 'AspectRatio',
    list: 'List',
    'typography-styles-provider': 'TypographyStylesProvider',
    'app-shell': 'AppShell',
    splitter: 'Splitter',
    space: 'Space',
    '--feedback': { type: 'separator', title: '反馈组件' },
    loader: 'Loader',
    overlay: 'Overlay',
    alert: 'Alert',
    skeleton: 'Skeleton',
    progress: 'Progress',
    'ring-progress': 'RingProgress',
    notification: 'Notification',
    notifications: 'Notifications',
    'loading-overlay': 'LoadingOverlay',
    indicator: 'Indicator',
    'empty-state': 'EmptyState',
    'copy-button': 'CopyButton',
    '--data': { type: 'separator', title: '数据展示' },
    accordion: 'Accordion',
    avatar: 'Avatar',
    'scroll-area': 'ScrollArea',
    badge: 'Badge',
    blockquote: 'Blockquote',
    breadcrumbs: 'Breadcrumbs',
    card: 'Card',
    code: 'Code',
    'data-list': 'DataList',
    divider: 'Divider',
    highlight: 'Highlight',
    image: 'Image',
    kbd: 'Kbd',
    mark: 'Mark',
    spoiler: 'Spoiler',
    table: 'Table',
    'table-of-contents': 'TableOfContents',
    'theme-icon': 'ThemeIcon',
    timeline: 'Timeline',
    '--overlay': { type: 'separator', title: '浮层组件' },
    'hover-card': 'HoverCard',
    popover: 'Popover',
    tooltip: 'Tooltip',
    dialog: 'Dialog',
    drawer: 'Drawer',
    modal: 'Modal',
    '--form': { type: 'separator', title: '表单组件' },
    'text-input': 'TextInput',
    textarea: 'Textarea',
    'password-input': 'PasswordInput',
    'number-input': 'NumberInput',
    checkbox: 'Checkbox',
    'checkbox-group': 'CheckboxGroup',
    radio: 'Radio',
    'radio-group': 'RadioGroup',
    switch: 'Switch',
    'native-select': 'NativeSelect',
    select: 'Select',
    'multi-select': 'MultiSelect',
    autocomplete: 'Autocomplete',
    'tags-input': 'TagsInput',
    slider: 'Slider',
    'range-slider': 'RangeSlider',
    rating: 'Rating',
    'segmented-control': 'SegmentedControl',
    chip: 'Chip',
    'pin-input': 'PinInput',
    'color-input': 'ColorInput',
    'file-button': 'FileButton',
    'file-input': 'FileInput',
    'json-input': 'JsonInput',
    'mask-input': 'MaskInput',
    fieldset: 'Fieldset',
    '--navigation': { type: 'separator', title: '导航组件' },
    burger: 'Burger',
    menu: 'Menu',
    affix: 'Affix',
    tabs: 'Tabs',
    pagination: 'Pagination',
    stepper: 'Stepper',
    'nav-link': 'NavLink',
    '--utils': { type: 'separator', title: '工具组件' },
    collapse: 'Collapse',
    'focus-trap': 'FocusTrap',
    portal: 'Portal',
    transition: 'Transition',
    'unstyled-button': 'UnstyledButton',
    'visually-hidden': 'VisuallyHidden'
}
