export default {
    index: '组件概览',
    '--basic': { type: 'separator', title: '基础组件' },
    button: 'Button',
    'action-icon': 'ActionIcon',
    'close-button': 'CloseButton',
    anchor: 'Anchor',
    text: 'Text',
    title: 'Title',
    '--layout': { type: 'separator', title: '布局组件' },
    container: 'Container',
    group: 'Group',
    stack: 'Stack',
    paper: 'Paper',
    center: 'Center',
    flex: 'Flex',
    'simple-grid': 'SimpleGrid',
    space: 'Space',
    '--feedback': { type: 'separator', title: '反馈组件' },
    loader: 'Loader',
    overlay: 'Overlay',
    '--data': { type: 'separator', title: '数据展示' },
    accordion: 'Accordion',
    'scroll-area': 'ScrollArea',
    badge: 'Badge',
    blockquote: 'Blockquote',
    breadcrumbs: 'Breadcrumbs',
    divider: 'Divider',
    '--navigation': { type: 'separator', title: '导航组件' },
    burger: 'Burger',
    '--utils': { type: 'separator', title: '工具组件' },
    collapse: 'Collapse',
    'focus-trap': 'FocusTrap',
    portal: 'Portal',
    transition: 'Transition',
    'unstyled-button': 'UnstyledButton',
    'visually-hidden': 'VisuallyHidden'
}
