import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, existsSync } from 'fs'
import { join, relative } from 'path'

/**
 * 扫描 demos/ 下所有 demo 文件，生成一个注册表 .docgen/demo-registry.ts。
 *
 * 设计要点（性能）：
 *  - 「真实源码」内联为字符串（JSON.stringify，全平台兼容，不依赖 ?raw loader），
 *    保证 <Demo demoId> 展示与运行同源、不漂移。
 *  - demo 组件本身**不静态 import**，而是保存一个动态 import() 函数 `load()`。
 *    这样打包器会把每个 demo 自动拆成独立 chunk，运行时按 demoId 按需加载，
 *    避免把所有 demo + 整个组件库塞进每个路由的依赖图。
 *
 * 重新生成：pnpm docs:gen（predev / prebuild 会自动触发）
 */

const ROOT = process.cwd()
const DEMOS_DIR = join(ROOT, 'demos')
const OUT_DIR = join(ROOT, '.docgen')
const OUT_FILE = join(OUT_DIR, 'demo-registry.ts')

function walk(dir: string): string[] {
    const out: string[] = []
    if (!existsSync(dir)) return out
    for (const name of readdirSync(dir)) {
        if (name === 'node_modules' || name.startsWith('.')) continue
        const full = join(dir, name)
        const st = statSync(full)
        if (st.isDirectory()) {
            out.push(...walk(full))
        } else if (/\.(tsx|ts)$/.test(name) && !/^index\.(tsx|ts)$/.test(name)) {
            out.push(full)
        }
    }
    return out
}

function main() {
    const files = walk(DEMOS_DIR).sort()
    const entries: string[] = []

    files.forEach(file => {
        const rel = relative(DEMOS_DIR, file).replace(/\\/g, '/')
        const importPath = rel.replace(/\.(tsx|ts)$/, '')
        const id = importPath.toLowerCase()
        const source = readFileSync(file, 'utf-8')
        entries.push(`  '${id}': { load: () => import('../demos/${importPath}'), code: ${JSON.stringify(source)} },`)
    })

    if (!existsSync(OUT_DIR)) mkdirSync(OUT_DIR, { recursive: true })

    const content = `/* AUTO-GENERATED by scripts/generate-demo-registry.ts — do not edit. */
import * as React from 'react'

export interface DemoEntry {
    /** 动态加载 demo 组件（打包器自动按 demo 拆分成独立 chunk） */
    load: () => Promise<{ default: React.ComponentType<any> }>
    /** 该 demo 的真实源码字符串，用于展示代码块 */
    code: string
}

export const demoRegistry: Record<string, DemoEntry> = {
${entries.join('\n')}
}
`

    writeFileSync(OUT_FILE, content, 'utf-8')
    console.log(`[demo-registry] Generated ${files.length} demos (lazy-loaded) -> ${OUT_FILE}`)
}

main()
