const CONTROL_LABELS: Record<string, string> = {
  variant: '变体',
  size: '尺寸',
  radius: '圆角',
  color: '颜色',
  label: '标签',
  description: '描述',
  error: '错误',
  placeholder: '占位符',
  disabled: '禁用',
  loading: '加载中',
  readOnly: '只读',
  required: '必填',
  withAsterisk: '必填标记',
  withError: '显示错误',
  withDescription: '显示描述',
  withLabel: '显示标签',
  autosize: '自动调整大小',
  minRows: '最小行数',
  maxRows: '最大行数',
  resize: '调整大小',
  rows: '行数',
  clearable: '可清空',
  searchable: '可搜索',
  creatable: '可创建',
  multiple: '多选',
  accept: '接受类型',
  icon: '图标',
  position: '位置',
  orientation: '方向',
  spacing: '间距',
  justify: '水平对齐',
  align: '对齐',
  grow: '拉伸',
  wrap: '换行',
  truncate: '截断',
  lineClamp: '行数限制',
  span: '跨度',
  offset: '偏移',
  order: '标题级别',
  weight: '字重',
  transform: '转换',
  decoration: '装饰',
  fs: '字号',
  c: '颜色',
  bg: '背景',
  opacity: '透明度',
  hiddenFrom: '在以下尺寸隐藏',
  visibleFrom: '在以下尺寸显示',
  w: '宽度',
  h: '高度',
  miw: '最小宽度',
  maw: '最大宽度',
  mih: '最小高度',
  mah: '最大高度',
  pl: '左内边距',
  pr: '右内边距',
  pt: '上内边距',
  pb: '下内边距',
  px: '水平内边距',
  py: '垂直内边距',
  ml: '左外边距',
  mr: '右外边距',
  mt: '上外边距',
  mb: '下外边距',
  mx: '水平外边距',
  my: '垂直外边距',
  p: '内边距',
  m: '外边距',
  fullWidth: '全宽',
  fullHeight: '全高',
  centered: '居中',
  checked: '选中',
  indeterminate: '不确定',
  defaultValue: '默认值',
  defaultChecked: '默认选中',
  value: '值',
  onChange: '变更回调',
  onClick: '点击回调',
  onFocus: '聚焦回调',
  onBlur: '失焦回调',
  children: '子元素',
  component: '组件',
  className: '类名',
  style: '样式',
  id: 'ID',
  name: '名称',
  type: '类型',
  title: '标题',
  href: '链接',
  target: '目标',
  rel: '关系',
  src: '来源',
  alt: '替代文本',
  width: '宽度',
  height: '高度',
  min: '最小值',
  max: '最大值',
  step: '步长',
  gradientFrom: '渐变起点',
  gradientTo: '渐变终点',
  gradientDegree: '渐变角度',
  gradient: '渐变',
  labelPosition: '标签位置',
  withIcon: '带图标',
  iconSize: '图标尺寸',
  stroke: '描边',
  inverted: '反转',
  deactivate: '停用',
  keyboardActivation: '键盘激活',
  preventGrowOverflow: '防止拉伸溢出',
  allowMultiple: '允许多选',
  loop: '循环',
  keepMounted: '保持挂载',
  unmountOnExit: '退出时卸载',
  activateOnFocus: '聚焦时激活',
  minLength: '最小长度',
  maxLength: '最大长度',
  pattern: '模式',
  autoComplete: '自动完成',
  autoFocus: '自动聚焦',
  tabIndex: 'Tab 索引',
  role: '角色',
  'aria-label': 'ARIA 标签',
  showLabelOnHover: '悬停时显示标签',
  labelAlwaysOn: '标签始终开启',
  labelTransitionProps: '标签过渡属性',
  minRange: '最小范围',
  maxRange: '最大范围',
  pushOnOverlap: '重叠时推动',
  restrictToMarks: '限制到刻度',
  marks: '刻度',
  domain: '取值域',
  scale: '缩放',
  thumbFromLabel: '起始滑块 ARIA 标签',
  thumbToLabel: '结束滑块 ARIA 标签',
  thumbValueText: '滑块值文本',
  transition: '过渡',
  duration: '持续时间',
  timingFunction: '计时函数',
  withTooltip: '带提示',
  loaderProps: '加载器属性',
  leftSection: '左侧区域',
  rightSection: '右侧区域',
  clearSectionMode: '清除区域模式',
};

function upperFirst(str: string) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

export function getControlLabel(label: string) {
  if (CONTROL_LABELS[label]) {
    return CONTROL_LABELS[label];
  }
  return upperFirst(label.replace(/([a-z])([A-Z])/g, '$1 $2').toLowerCase());
}
