// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/zhangzhengyang/Desktop/Code/react/UI/react-ui/node_modules/.pnpm/dumi-plugin-color-chunk@2.1.0_@babel+core@7.28.4_@swc+helpers@0.5.15_@types+node@26.1.1_@type_q6d2eqrsfofk7npboywqw4b4si/node_modules/dumi-plugin-color-chunk/es/component/index.js';
export * from '/Users/zhangzhengyang/Desktop/Code/react/UI/react-ui/node_modules/.pnpm/dumi-plugin-color-chunk@2.1.0_@babel+core@7.28.4_@swc+helpers@0.5.15_@types+node@26.1.1_@type_q6d2eqrsfofk7npboywqw4b4si/node_modules/dumi-plugin-color-chunk/es/component/index.js';
